# Generated by Django 5.0.3 on 2024-04-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='last_analyzed',
        ),
        migrations.AddField(
            model_name='repository',
            name='son_analiz_zamani',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Analiz Zamanı'),
        ),
        migrations.CreateModel(
            name='JavaDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_adi', models.CharField(max_length=255, verbose_name='Sınıf Adı')),
                ('javadoc_yorum_satir_sayisi', models.IntegerField(default=0, verbose_name='Javadoc Yorum Satır Sayısı')),
                ('yorum_satir_sayisi', models.IntegerField(default=0, verbose_name='Yorum Satır Sayısı')),
                ('kod_satir_sayisi', models.IntegerField(default=0, verbose_name='Kod Satır Sayısı')),
                ('toplam_satir_sayisi', models.IntegerField(default=0, verbose_name='Toplam Satır Sayısı (LOC)')),
                ('fonksiyon_sayisi', models.IntegerField(default=0, verbose_name='Fonksiyon Sayısı')),
                ('yorum_sapma_yuzdesi', models.FloatField(default=0.0, verbose_name='Yorum Sapma Yüzdesi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='java_dosyalari', to='my_app.repository', verbose_name='Depo')),
            ],
        ),
        migrations.DeleteModel(
            name='JavaFile',
        ),
    ]
